# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JSBridgeDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JSBridgeDemo
  
  pod 'WebViewJavascriptBridge',:inhibit_warnings => true
  pod 'JSWebKit', :path => '../JSWebKit',:inhibit_warnings => true
  pod 'DKResourceLinkKit', :path => '../DKResourceLinkKit'
  
  target 'JSBridgeDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JSBridgeDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  #解决weak不能用问题
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
